# Generated by Django 4.0.10 on 2023-03-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservote',
            name='sex',
        ),
    ]
