# Generated by Django 4.0.10 on 2023-03-16 14:14

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_uservote_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='uservote',
            name='language',
        ),
        migrations.RemoveField(
            model_name='uservote',
            name='services',
        ),
        migrations.AddField(
            model_name='uservote',
            name='services',
            field=models.ManyToManyField(blank=True, to='users.service'),
        ),
        migrations.AddField(
            model_name='uservote',
            name='language',
            field=models.ManyToManyField(blank=True, to='users.language'),
        ),
        migrations.CreateModel(
            name='LanguageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50, verbose_name='Language')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='users.language')),
            ],
            options={
                'verbose_name': 'language Translation',
                'db_table': 'users_language_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
