# Generated by Django 4.0.10 on 2023-03-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_country_uservote_country_countrytranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='percent',
            field=models.FloatField(default=0),
        ),
    ]
