# Generated by Django 4.0.10 on 2023-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_uservote_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
