# Generated by Django 4.0.10 on 2023-03-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_uservote_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
