# Generated by Django 4.0.10 on 2023-03-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_category_page_alter_useranswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'CHOICE'), ('CHECKBOX', 'CHECKBOX'), ('NUMBER', 'NUMBER'), ('AGE', 'AGE')], default='CHOICE', max_length=10),
        ),
    ]
