# Generated by Django 4.0.10 on 2023-03-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.page'),
            preserve_default=False,
        ),
    ]
