# Generated by Django 4.0.10 on 2023-03-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
    ]
